name: Python/RL-Learning CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install yaml
        run: pip install yaml
      - name: run agent training
        run: ./launch.sh
